### ISSUE TITLE
Webplate Responsive Navigation

### ISSUE THREAD

**Issue by neo-art** [chrishumboldt/Webplate#71]
Hi,

I am using the Webplate stack for one of my projects and I really love the responsive
triggered menu. I am working on a new project and I was wondering if it is possible to
use Flickerplate with the navigation only (as a separated plugin perhaps? )?
I downloaded Flickerplate separately but can't find the navigation js.

**Comment by chrishumboldt** [comment]
Hey Neo.

In case you were still wondering you can now use the navigation component as a seperate "plugin". It can be found at https://github.com/chrishumboldt/Navplate.

Keep Well
