### ISSUE TITLE
display some kind of loading till website is hidden

### ISSUE THREAD

**Issue by agauniyal** [chrishumboldt/Webplate#74]
Sometimes , and reproducible with slow network connections , webplate website will load blank and will  not show any progress till background image is loaded. This behavior makes user assume that website is broken. 

Displaying some kind of loading activity till hidden is unset on body will likely fix this issue. And congratulations , this is a great project :smile:

**Comment by chrishumboldt** [comment]
Hi

Glad you dig the project and I will definitely take the comment into consideration. Seeing nothing is a bad interaction and you make a very valid point. I will change this into a feature update.

Thanks
C
