### ISSUE TITLE
XMLHttpRequest cannot load 

### ISSUE THREAD

**Issue by ossanti** [chrishumboldt/Webplate#84]
I opened up the file after installing (successfully) webplate command tools. Thats what happens when I open the index file after a clean download/installation.

**Comment by ossanti** [comment]
i fixed this by running a local server, i fixed it using CodeKit, it also works with Gulp Webserver or any plugin thats gives you a localhost:800

**Comment by chrishumboldt** [comment]
Ok nice. At least you were able to run the instance.
